### ISSUE TITLE
test: Write unit tests for FlexStakingPool

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#79] opened 2024-08-21 17:33 UTC
Complete the unit test of `stakingpool/FlexStakingPool.cairo`, write test cases in `stakingpool/tests` folder.

Use `scarb test` to run all the tests.

All test cases are required to `PASS`.

**Comment by od-hunter** [comment] 2024-08-21 17:34
U

**Comment by ooochoche** [comment] 2024-08-21 17:36
@0xandee I’m available to work on this

**Comment by ShantelPeters** [comment] 2024-08-21 17:36
Hi @0xandee please can I work on this issue once OD hack commences tomorrow please

**Comment by Oshioke-Salaki** [comment] 2024-08-21 19:22
Pleaseeeeeee sir/ma I want to solve this issue and contribute to this project.

**Comment by EmmanuelAR** [comment] 2024-08-21 22:41
Heyyy @0xandee can i work on this??
I will
	1.	Review the Contract: Understand the logic and functions of FlexStakingPool.cairo.
	2.	Write Tests:
	•	Go to openedition/tests and create a test file for FlexStakingPool.cairo.
	•	Write test cases that cover all functions, including normal operation, edge cases, and failure scenarios.
	3.	Run Tests:
	•	Use the scarb test command to run all the tests.
	4.	Debug:
	•	If any tests fail, review and adjust the test cases or contract as needed, then rerun until all tests pass.
	5.	Final Steps:
	•	Ensure everything is documented and submit your work.

**Comment by wugalde19** [comment] 2024-08-22 07:42
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi Flex Marketplace team,
I’m William from Costa Rica 🇨🇷 and member of the Dojo Coding community.
I am interested in contributing to this issue and believe my skills and background make me well-suited for the task. I’ve worked over 7 years as Full Stack engineer in several technologies (including the ones used on this project JS, and Typescript) and I am currently expanding my expertise in Rust, Cairo, and Solidity.

I’ve participated in two past OD Hack events and the StarkHack event organized by ETHGlobal.
In the StarkHack, we tried to develop an dApp to interact with NFTs in Starknet.

And that’s why I’m interested on this project, because it relates to what our old team tried back then. Also interested on learning more about your team and contribute

Profiles:
https://app.onlydust.com/u/wugalde19

https://github.com/wugalde19


### How I plan on tackling this issue
The way I’d approach this is by:
First, follow the Readme to set up the project locally.
Take a full day to really understand the logic inside of “stakingpool/FlexStakingPool.cairo” file.
Ask questions in the Telegram channel (if any).
Then, start writing tests following best practices and examples in Cairo book documentation and other projects I have contributed to before.
Run all the tests on this project to make sure all test still pass.
Open a PR with all the new tests into the “stakingpool/tests” folder.
And finally, after your first review of that PR, take the feedback, iterate over my implementation based on the feedback that you guys provided, and at the end of the cycle deliver good quality tests and get a good coverage % on your project

**Comment by EmmanuelAR** [comment] 2024-08-22 08:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Heyyyy @0xandee can i work on this??? I’m Emmanuel Software Dev from Dojo coding and Costa Rica 


### How I plan on tackling this issue
I will..
1.⁠ ⁠Review the Contract: Understand the logic and functions the contracts 
2.⁠ ⁠Write Tests:
•⁠  ⁠Go to openedition/tests and create a test file for the contracts 
•⁠  ⁠Write test cases that cover all functions, including normal operation, edge cases, and failure scenarios.
3.⁠ ⁠Run Tests:
•⁠  ⁠Use the scarb test command to run all the tests.
4.⁠ ⁠Debug:
•⁠  ⁠If any tests fail, review and adjust the test cases or contract as needed, then rerun until all tests pass.
5.⁠ ⁠Final Steps:
•⁠  ⁠Ensure everything is documented and submit your work.

**Comment by PoulavBhowmick03** [comment] 2024-08-22 08:09
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

### How I plan on tackling this issue
1. Understand the Contract's Functionality
The FlexStakingPool contract includes several key functions: stakeNFT, unstakeNFT, getUserPointByItem, getUserTotalPoint, and several setters like setAllowedCollection, setTimeUnit, and setRewardPerUnitTime.
These functions involve interactions with ERC721 tokens, ownership checks, reentrancy protections, and calculations related to staking rewards.
2. Set Up Your Test Environment
Create a new test file in the stakingpool/tests folder, for example, test_flex_staking_pool.cairo.
Import necessary modules such as pytest, starknet, and the contract itself.
Use fixtures to deploy your contract and set up any required initial state (e.g., setting the owner, defining eligible collections).
3. Write Test Cases
Constructor Test:
Test that the contract is correctly initialized with the specified owner.
Stake NFT Test:
Test staking an NFT by verifying that the ItemStaked event is emitted, the vault is updated, and the NFT is transferred to the contract.
Test edge cases such as staking an already staked NFT or staking from a non-owner address.
Unstake NFT Test:
Test unstaking an NFT by verifying that the ItemUnstaked event is emitted, the vault is cleared, and the NFT is transferred back to the owner.
Ensure points are correctly claimed when unstaking.
Points Calculation Test:
Test the _calculateUnclaimedPoint and _calculateTotalReward functions to ensure they accurately calculate rewards based on the staking duration, time unit, and reward per unit time.
Admin Functions Test:
Test the setAllowedCollection, setTimeUnit, and setRewardPerUnitTime functions to ensure they correctly update the contract's state and enforce ownership checks.
Reentrancy Protection Test:
Ensure that the start and end functions of the reentrancy guard are correctly applied and prevent reentrant calls.
4. Run and Debug
Run the tests using scarb test.
Debug any failing tests by checking the error messages and reviewing the contract logic.

**Comment by manlikeHB** [comment] 2024-08-22 08:10
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi, I am cairo developer with lots of experience writing test for cairo contracts. You can take a look at my progile to see some of the projects I have contributed to in previous OD  Hacks.

### How I plan on tackling this issue
- I will go through the repo to get a better understanding of the project.
- I will fork then clone the repo and set it up locally.
- i will go through the FlexStakingPool contract and identify the test cases.
- Then I will write a robust test for all the test cases as well as that of the events emitted and ensure they all pass.
- Provide comments for aspect that are not clear and then format the code with scarb.

**Comment by sotoyjuan** [comment] 2024-08-22 08:21
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hey! I'd like to collaborate on this project. I have five years of development experience, I'm currently going through a Starknet bootcamp with Dojo Coding, which provides me with the foundational knowledge needed. I believe this combination of my experience and current training makes me well-suited to tackle this issue. I've already contributed to another project. Thanks for considering me.

**Comment by LazarusAA** [comment] 2024-08-22 09:20
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
My last contribution was about implementing tests for hints in Cairo, I believe I can leverage that experience for this issue

### How I plan on tackling this issue
- Read and understand the contracts logic
- Create adequate tests for FlexStakingPool
- Check that all tests "PASS" correctly before merging

**Comment by ScottyDavies** [comment] 2024-08-22 10:50
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a blockchain developer. 
With background on JavaScript

### How I plan on tackling this issue
Understanding the Codebase: First, I would try to understand the existing codebase, particularly the FlexStakingPool.cairo file and any related files or dependencies. This would involve reading through the code, understanding the structure, and familiarizing myself with the overall functionality of the staking pool contract.
Reviewing the Existing Tests: Next, I would examine the existing test cases in the stakingpool/tests folder. I would try to understand the purpose of each test case, the scenarios they cover, and the expected outcomes. This would help me identify any gaps or areas that need further testing.
Identifying Test Cases: Based on the understanding of the contract's functionality and the existing test cases, I would identify additional test cases that need to be added. These test cases should cover various scenarios, including edge cases and potential failure conditions. For example, I might want to test the following:
Successful staking and unstaking of tokens
Handling of multiple stakers
Correct calculation of rewards
Handling of contract pauses or emergencies
Behavior when the contract reaches certain thresholds (e.g., maximum number of stakers)
Writing Test Cases: Once the test cases have been identified, I would proceed to write the actual test cases in the stakingpool/tests folder. I would use the Scarb testing framework to create comprehensive and easily maintainable test suites.
Running the Tests: After writing the test cases, I would use the scarb test command to run all the tests, including the existing ones and the new ones I added. I would ensure that all the tests pass and that the test coverage is satisfactory.
Refactoring and Improving the Tests: If any of the tests fail, I would investigate the issues, identify the root causes, and update the test cases or the contract code accordingly. I would also look for opportunities to improve the test cases, making them more robust, expressive, and maintainable.
Continuous Integration and Deployment: As a frontend developer, I would work closely with the backend team to integrate the tested and approved staking pool contract into the overall application. I would ensure that the contract is properly integrated into the frontend and that the user interface seamlessly interacts with the contract's functionality.
Monitoring and Maintenance: Even after the initial deployment, I would continue to monitor the contract's performance, gather user feedback, and identify any issues or new requirements. I would work with the backend team to update the test cases and the contract code as needed, ensuring the staking pool remains reliable and up-to-date.

**Comment by ShantelPeters** [comment] 2024-08-22 12:14
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
To address the application form question and highlight how your background as a frontend developer can be relevant to completing the unit tests for `FlexStakingPool.cairo`, you can focus on your experience with testing, coding practices, and attention to detail. Here’s how you might respond:

---

As a frontend developer, my background equips me with a solid understanding of coding practices, attention to detail, and experience with testing frameworks, which are all highly relevant to completing the unit tests for `FlexStakingPool.cairo`. Here’s how my skills and experience will be leveraged for this task:

### Relevant Skills and Experience:

1. **Experience with Testing Frameworks**:
   - **Frontend Testing**: In my frontend development work, I regularly write and execute unit tests using frameworks like Jest and Mocha. This experience has honed my ability to create comprehensive test cases, ensuring that each part of the code functions correctly and meets the requirements.
   - **Understanding Testing Best Practices**: I am familiar with best practices in writing clear, maintainable, and effective tests. This includes ensuring that tests are both thorough and efficient, covering various edge cases and potential failure points.

2. **Coding and Debugging Skills**:
   - **Attention to Detail**: My experience in frontend development requires a high level of attention to detail, particularly when debugging and ensuring that user interfaces function as expected. This skill translates well to writing unit tests, where careful consideration of each test case and its expected outcomes is crucial.
   - **Code Quality**: I am accustomed to following coding standards and practices that enhance readability and maintainability. This includes writing clean code and ensuring that test cases are well-organized and easy to understand.

3. **Understanding of Code Functionality**:
   - **Analytical Skills**: My background involves analyzing and understanding complex codebases and ensuring that all functionality is covered by tests. I can apply these skills to the `FlexStakingPool.cairo` contract, understanding its logic and ensuring that all relevant scenarios are tested.

### Approach to Completing the Unit Tests:

1. **Review the Contract**:
   - **Understand Functionality**: Begin by thoroughly reviewing the `FlexStakingPool.cairo` contract to understand its functions, requirements, and any specific behaviors that need to be tested.
   - **Identify Key Areas**: Identify the key functions and scenarios that need to be tested, including edge cases and potential failure points.

2. **Write Comprehensive Test Cases**:
   - **Create Test Cases**: Write detailed test cases for each function in the contract, ensuring that all possible scenarios are covered. This includes testing typical use cases, boundary conditions, and invalid inputs.
   - **Use Scarab**: Utilize the `scarb` testing framework as specified to implement and run the tests. Ensure that the tests are structured according to the framework's requirements and conventions.

3. **Run and Validate Tests**:
   - **Execute Tests**: Run all test cases using `scarb test` to ensure that they pass and verify that the contract behaves as expected.
   - **Debug and Fix Issues**: If any tests fail, debug the issues, make necessary fixes to either the contract or the tests, and re-run the tests until all are passing.

4. **Document Test Cases**:
   - **Update Documentation**: Document the test cases and any important details about the testing process. This includes explaining what each test case covers and how it contributes to validating the contract's functionality.

5. **Ensure All Tests Pass**:
   - **Complete the Testing**: Ensure that all test cases pass successfully before finalizing the work. This guarantees that the contract functions as intended and meets all specified requirements.

### How I plan on tackling this issue
To complete the unit tests for `stakingpool/FlexStakingPool.cairo`, follow a systematic approach to ensure that all test cases are comprehensive and the tests pass successfully. Here's how I would approach the problem:

### 1. **Understand the Contract**
   - **Review the Contract Code**: Start by thoroughly reviewing the `FlexStakingPool.cairo` contract code. Understand its functionality, the key functions, and how the contract operates.
   - **Identify Key Functions**: Note the functions and features that need to be tested, such as staking, unstaking, rewards calculation, and any specific logic unique to the contract.

### 2. **Set Up the Testing Environment**
   - **Navigate to the Tests Folder**: Ensure that the `stakingpool/tests` folder is set up correctly for writing and organizing the test cases.
   - **Familiarize with Scarab**: Confirm that `scarb` (or the testing tool specified) is installed and properly configured for running the tests. Review its documentation to understand how to write and run tests using this framework.

### 3. **Write Test Cases**
   - **Create a Test Plan**: Outline a test plan that includes various scenarios to cover:
     - **Basic Functionality**: Ensure that core functionalities like staking and unstaking are tested.
     - **Edge Cases**: Test boundary conditions and edge cases such as staking with zero amount or exceeding limits.
     - **Error Handling**: Verify how the contract handles invalid inputs or errors.
     - **Rewards Calculation**: Test if the rewards calculation is accurate based on different scenarios.
   - **Implement Test Cases**: Write the test cases in the `stakingpool/tests` folder:
     - **Initialize State**: Set up the initial state required for each test case, including deploying the contract and setting up necessary parameters.
     - **Execute Functions**: Call the functions of the contract and check if the outputs match the expected results.
     - **Verify Results**: Assert that the results from the contract match expected values, including balances, rewards, and any other relevant metrics.

### 4. **Run the Tests**
   - **Execute Tests Using Scarab**: Run the tests using the `scarb test` command to execute all the test cases. Ensure that the tests are running in the correct environment and that any dependencies are met.
   - **Monitor Results**: Check the test results for any failures or issues. Review the output to understand if and where tests are failing.

### 5. **Debug and Fix Issues**
   - **Analyze Failures**: If any tests fail, analyze the failures to determine whether they are due to issues in the contract code or the test cases themselves.
   - **Fix Issues**: Correct any issues found, whether they are in the contract logic or in the test case implementations. This may involve debugging the contract or adjusting the test cases.

### 6. **Validate and Finalize**
   - **Re-run Tests**: After making corrections, re-run the tests to ensure that all issues are resolved and that all test cases pass.
   - **Ensure Comprehensive Coverage**: Double-check that all important aspects of the contract are covered by the tests, and that the tests are comprehensive.

### 7. **Document the Testing Process**
   - **Update Test Documentation**: Document the test cases, what they cover, and any relevant details about the testing process. This helps in maintaining clarity for future reference or for other developers.

### 8. **Prepare for Deployment**
   - **Final Review**: Conduct a final review of the contract and test cases to ensure everything is in order before moving forward.
   - **Run Tests in CI/CD**: If applicable, integrate the tests into a continuous integration/continuous deployment (CI/CD) pipeline to ensure ongoing test coverage

**Comment by DiegoB1911** [comment] 2024-08-22 13:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience, primarily working with Next.js. I'm also a member of Dojo Coding, where I'm learning new things such as Cairo and Web3. This is my first time participating in an OD Hack, and I'm eager to learn and contribute to new projects.

### How I plan on tackling this issue
To address the task, I would follow these steps:

Understand the FlexStakingPool contract.
Write comprehensive test cases.
Ensure all tests pass.
Final verification,  I would perform a final review to ensure that the tests are comprehensive.

**Comment by Abeeujah** [comment] 2024-08-22 16:01
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a Web and Systems engineer, with deep understanding of clean code principles and best practices, this has enabled me build resilient solutions backed by high quality tests and maxxed code coverage using TDD.

### How I plan on tackling this issue
- Understand the requirements for every functions
- Assert that the functions perform their tasks and meet the requirements
- Use multiple test cases to ensure every edge cases are covered.

**Comment by CollinsC1O** [comment] 2024-08-22 16:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm both a frontend and smart contract developer, I leverage my dual expertise to build robust projects and deliver tangible solutions. My experience in frontend development enables me to create intuitive user interfaces, while my skills in smart contract development allow me to design and implement secure, efficient blockchain solutions. 

### How I plan on tackling this issue
To write unit tests for the FlexStakingPool using Cairo Testing, the steps below will be followed :

Set Up Cairo Environment:
- Ensure you have Cairo installed and configured for your project.

Create Test File:
- Create a test file named test_flex_staking_pool.cairo in your test directory.

Write Test Cases:
-Initialization: Verify that FlexStakingPool initializes correctly and defaults are set properly.
  
Functionality: Test core functions such as staking, withdrawing, and checking balances.

Edge Cases: Handle scenarios like invalid inputs, boundary conditions, and state transitions.

Run Tests:
- Use the Cairo CLI or testing tool to execute the test cases and verify the results.

Review Results:
- Check test outputs, ensure all tests pass, and debug any issues if tests fail.
- Adapt the test cases to match the actual implementation and functionality of the FlexStakingPool component in your project.

**Comment by MullerTheScientist** [comment] 2024-08-22 20:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a full-stack developer with experience in different languages, such as Python, Cairo, Solidity, and JavaScript.

### How I plan on tackling this issue
I will understand the requirements:
I will Write unit tests for FlexStakingPool.cairo in the stakingpool/tests folder.
Use scarb test to run all tests.
Ensure all test cases pass.

**Comment by DiegoB1911** [comment] 2024-08-23 19:23
Thank you for assigning me the issue. I am working on it right now.

**Closed** 2024-09-02 06:22 UTC
Labels: good first issue, Type: test, Techno: cairo, ODHack7
