### ISSUE TITLE
[Experimental] [POC] ERC-6806 Holding Time Tracking

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#123] opened 2024-10-23 21:31 UTC
Create and work inside folder `experimental/erc_6806_holding_time_tracking`:

It adds an interface that tracks and describes the holding time of a Non-Fungible Token (NFT) by an account. 

**Implementation Details:**
- The design and approach are left to the discretion of the assignee.
- In some use cases, it is valuable to know the duration for which a NFT has been held by an account. This information can be useful for rewarding long-term holders, determining access to exclusive content, or even implementing specific business logic based on holding time. However, the current ERC-721 standard does not have a built-in mechanism to track NFT holding time.

**Reference:** https://github.com/ethereum/ERCs/blob/60569a1f8b57fea10340dc34602baf895a613daa/ERCS/erc-6806.md

**Comment by raizo07** [comment] 2024-10-23 21:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hello, I'll like to be assigned to work on this.

**Comment by codeZe-us** [comment] 2024-10-23 21:43
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
To address this, I will extend the NFT standard by implementing a function that logs transfer timestamps and calculates the holding duration for each account.

**Comment by Iwueseiter** [comment] 2024-10-24 00:42
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a frontend and smart contract developer. 

### How I plan on tackling this issue
To tackle this task, I'd first create a folder `experimental/erc_6806_holding_time_tracking` where I will be working.

I'd create an interface to track the holding time of  NFTs for each owner by extending the existing ERC-721 standard functionality.

I will implement logic to record the timestamp of when an NFT is transferred to an account.

I will implement a mechanism to  track NFT holding time. This mechanism will ensure to calculate how long an account has held a specific NFT. If the NFT has been transferred to a new owner, the holding time is reset and only accounts for the duration of the current owner’s holding period.
A mapping will store the start of the ownership; it's ID, the `Owner address`  and the timestamp when the account acquired the NFT.
 
I'd ensure to reference : https://github.com/ethereum/ERCs/blob/60569a1f8b57fea10340dc34602baf895a613daa/ERCS/erc-6806.md as expected.

ETA: 48hrs

**Comment by JoE11-y** [comment] 2024-10-24 07:38
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm Joseph a blockchain developer with over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

1. Study current codebase design
2. Leverage all provided resources within the issue to get a better grasp of the task at hand.
3. Implement the task.
4. Add tests to make sure the changes are working and no adverse effects
5. And lastly optimize

**Comment by martinvibes** [comment] 2024-10-24 07:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by ShantelPeters** [comment] 2024-10-24 08:09
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am frontend and blockchain developer , and  My background in blockchain and smart contract development enables me to design this functionality efficiently, ensuring compatibility with the existing NFT ecosystem while adding value for real-world use cases.

### How I plan on tackling this issue
To solve the issue of implementing ERC-6806 for holding time tracking, I would extend the ERC-721 standard to include a function that logs the timestamp whenever an NFT is transferred to a new account. The contract would store the holding start time for each NFT, and calculate the holding duration when needed. This feature would allow developers to implement reward systems for long-term holders or trigger business logic based on the duration.

**Comment by saimeunt** [comment] 2024-10-24 08:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past, porting Solidity ERCs to Cairo eg. https://github.com/carbonable-labs/cairo-erc-7496 and https://github.com/carbonable-labs/cairo-erc-7498

### How I plan on tackling this issue
I will carefully read the ERC and proposed Solidity implementation and I'll implement the expected behavior in Cairo. I will then use Starknet Foundry to test if the implementation is correct.

**Comment by 0xandee** [comment] 2024-10-28 08:41
GM @codeZe-us  just checking in, how're you doing?

**Comment by codeZe-us** [comment] 2024-10-28 20:10
> GM @codeZe-us  just checking in, how're you doing?

Gm. I am good.

**Comment by Mystic-Nayy** [comment] 2024-11-09 05:35
@0xandee Please can i be assigned to work on this ?
I am an experienced cairo developer

**Comment by remybar** [comment] 2024-11-09 08:13
Hi @0xandee !

I'm still available to work on one of the pending [Experimental] tasks ! I'm an experienced Cairo developer who actively contribute to OD projects (mainly to Dojo since beginning of this year). I'm also active on the cairo channel of the Starknet discord.

I don't want to spam you on all [Experimental] tasks so if you need some help on one of them, feel free to ping me/assign it to me :)

**Comment by SailorJhay** [comment] 2024-11-09 08:40
Hello @0xandee,  Before I request to give this a shot I want to confirm,

Are going to be keeping a historical track of holders and how long they held by NFT or just the current holder

The EIP is suggesting just the current holder
```sol
interface IERC6806 {
    function getHoldingInfo(
        uint256 tokenId
    ) external view returns (address holder, uint256 holdingTime);
}
```

I would be able to complete this within the weekend if I am assigned

**Comment by saimeunt** [comment] 2024-11-09 14:39
Hey @0xandee as a returning contributor I'd like to handle this one please!

**Comment by Iwueseiter** [comment] 2024-11-10 16:46
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).
> 
> ### My background and how it can be leveraged
> I'm a frontend and smart contract developer.
> 
> ### How I plan on tackling this issue
> To tackle this task, I'd first create a folder `experimental/erc_6806_holding_time_tracking` where I will be working.
> 
> I'd create an interface to track the holding time of NFTs for each owner by extending the existing ERC-721 standard functionality.
> 
> I will implement logic to record the timestamp of when an NFT is transferred to an account.
> 
> I will implement a mechanism to track NFT holding time. This mechanism will ensure to calculate how long an account has held a specific NFT. If the NFT has been transferred to a new owner, the holding time is reset and only accounts for the duration of the current owner’s holding period. A mapping will store the start of the ownership; it's ID, the `Owner address` and the timestamp when the account acquired the NFT.
> 
> I'd ensure to reference : https://github.com/ethereum/ERCs/blob/60569a1f8b57fea10340dc34602baf895a613daa/ERCS/erc-6806.md as expected.
> 
> ETA: 48hrs

Can I work on this task?

**Comment by ShantelPeters** [comment] 2024-11-11 12:05
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).
> 
> ### My background and how it can be leveraged
> I am frontend and blockchain developer , and My background in blockchain and smart contract development enables me to design this functionality efficiently, ensuring compatibility with the existing NFT ecosystem while adding value for real-world use cases.
> 
> ### How I plan on tackling this issue
> To solve the issue of implementing ERC-6806 for holding time tracking, I would extend the ERC-721 standard to include a function that logs the timestamp whenever an NFT is transferred to a new account. The contract would store the holding start time for each NFT, and calculate the holding duration when needed. This feature would allow developers to implement reward systems for long-term holders or trigger business logic based on the duration.

Can i please work on this task @0xandee

**Comment by martinvibes** [comment] 2024-11-20 15:47
hey @0xandee i messaged you on discord please check

**Closed** 2024-12-02 14:47 UTC
Labels: good first issue, Difficulty: easy, ODHack9
