### ISSUE TITLE
feat: Implement strategy_any_item_from_collection_for_fixed_price contract

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#83] opened 2024-08-21 18:12 UTC
This strategy will allow buyer can set a fixed price, then any NFT holder can insant sell at that price.

Read more on `README`, `marketplace/deployment.ts` and `strategy_standard_sale_for_fixed_price.cairo` for references and to understand more how strategy works with marketplace contract.

Example feature image: 

<img width="755" alt="image" src="https://github.com/user-attachments/assets/4f893375-fc27-41ad-b825-fe363f05e49a">

**Comment by Gift-Naomi** [comment] 2024-08-21 18:13
Hi

**Comment by ShantelPeters** [comment] 2024-08-21 18:18
Hi @0xandee can I be assigned to this

**Comment by mubarak23** [comment] 2024-08-21 19:06
am available to wo

**Comment by mubarak23** [comment] 2024-08-22 07:45
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.


My recent work with cairo starknet
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/dojoengine/dojo/pull/1912
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/BlockheaderWeb3-Community/dauction-starknet/pull/4


### How I plan on tackling this issue
I intent to handle via the following flow 
- Setting the Protocol Fee  
The contract will initially set the protocol fee via the constructor, and it will be managed by the contract owner. I will also add a function that allows the contract owner to update the protocol fee as needed.

- Returning the Protocol Fee:  
There will be a function to return the protocol fee. When an item is sold, the protocol fee will be added to the total price.

- Setting Items for Sale:
The contract will allow NFT holders to put items up for sale at any price. I will store the data in a mapping of `tokenId` to the owner's address.

- Setting the Price for Items: 
A function will allow buyers to set a price for an item. The function will return a tuple containing the `tokenId`, price, and buyer’s address. It will check if the item was put up for sale by the owner at any price and emit an event.

- can_execute_taker_bid:  
This function will return a tuple containing the price, `tokenId`, and a boolean indicating whether the bid can be executed. It will check if the item is allowed to be sold at the set price and emit an event.

- Upgrade Function:
This function will handle upgrading the contract.

Storage:  
- Mapping: `<tokenId, ownerAddress>`
- Mapping: `<buyerAddress, <TokenId, price>>`

Unit Tests: 
I will write all necessary unit tests, including edge cases for each function.

Duration:
4 days

**Comment by ScottyDavies** [comment] 2024-08-22 10:00
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am front end developer with 6 years experience. 
i have worked with microsoft on several projects,
this will be my first time contributing to the ecosystem and i am ready to work




### How I plan on tackling this issue
I would approach this issue with following steps
Understand the Existing Marketplace and Strategy:
Review the README file to gain a high-level understanding of how the marketplace contract and the various sales strategies work.
Examine the marketplace/deployment.ts file to see how the marketplace contract is currently being deployed and configured.
Analyze the strategy_standard_sale_for_fixed_price.cairo file to understand the implementation of the existing fixed-price sale strategy.
Design the Buyer-Set Fixed Price Strategy:
Determine the key components and requirements of the buyer-set fixed price strategy, such as:
Allowing buyers to set a fixed price for a specific NFT item
Enabling any NFT holder to instantly sell their NFT at the buyer-set price
Handling the transfer of the NFT and funds during the sale
Maintaining the buyer-set price and associated data
Sketch out the high-level logic and data structures needed to implement the buyer-set fixed price strategy.
Implement the Buyer-Set Fixed Price Strategy:
Create a new Cairo file, e.g., strategy_buyer_set_fixed_price.cairo, to implement the buyer-set fixed price strategy.
Define the necessary data structures and storage variables to keep track of the buyer-set prices, such as a mapping of NFT IDs to the fixed prices.
Implement the core logic of the buyer-set fixed price strategy, including:
Allowing buyers to set a fixed price for a specific NFT item
Enabling NFT holders to instantly sell their NFT at the buyer-set price
Handling the transfer of the NFT and funds during the sale
Updating the buyer-set price data when a sale occurs
Integrate the Buyer-Set Fixed Price Strategy with the Marketplace:
Modify the marketplace/deployment.ts file to include the new buyer-set fixed price strategy alongside the existing fixed-price sale strategy.
Ensure that the marketplace contract can properly interact with the buyer-set fixed price strategy, including:
Passing the necessary parameters to the buyer-set fixed price strategy
Handling the execution of the buyer-set fixed price sale
Integrating the buyer-set fixed price sale outcome with the overall marketplace functionality
Update the Documentation:
Enhance the README file to include detailed documentation on the new buyer-set fixed price strategy, covering the following aspects:
Overview of the buyer-set fixed price strategy and its key features
Integration with the marketplace contract
Step-by-step instructions on how to use the buyer-set fixed price strategy
Examples of buyer-set price setup and sale execution
Considerations and potential edge cases
Test and Validate the Buyer-Set Fixed Price Strategy:
Thoroughly test the buyer-set fixed price strategy, including various scenarios such as:
Buyers setting fixed prices for different NFT items
NFT holders attempting to sell at the buyer-set prices
Edge cases, such as handling errors or exceptions during the buyer-set fixed price sale
Ensure that the buyer-set fixed price strategy integrates seamlessly with the marketplace contract and that the overall system behaves as expected.
Deploy and Communicate the Changes:
Once the buyer-set fixed price strategy is tested and validated, deploy the updated marketplace contract to the production environment.
Communicate the new buyer-set fixed price functionality to the marketplace users, providing clear instructions and examples on how to set fixed prices and participate in the instant sale process.
Gather feedback from the users and be prepared to address any issues or concerns that arise during the initial deployment.

**Comment by kfastov** [comment] 2024-08-22 11:32
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I've wrote several Cairo contracts before, both from scratch and porting code from Solidity. I am aware of the latest Cairo updates, so I can write the up-to-date code.

### How I plan on tackling this issue
I will check the README on how the strategies work, than take an existing strategy as a reference, create a new file for the new strategy, and implement the code.
Then I'll look how I can integrate this strategy into existing flow and do it.

**Comment by ooochoche** [comment] 2024-08-22 12:43
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a smart contract developer

### How I plan on tackling this issue
I would start:

- first by designing the new strategy. It should allow a buyer to set a fixed price for NFTs, and NFT holders can instantly sell at that price. Use the references to guide your implementation.

- then, write the code in Cairo. Make sure it works well with the existing marketplace contract. 

- test the strategy carefully to check for any issues.

- review work and update the documentation if needed

**Closed** 2024-09-04 09:54 UTC
Labels: Type: feature, Techno: cairo, ODHack7
