### ISSUE TITLE
[Experimental] [POC] ERC-5173 NFT Future Rewards (nFR)

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#122] opened 2024-10-23 21:28 UTC
Create and work inside folder `experimental/erc_5173_future_rewards`:

nFR allows owners to benefit from future price appreciation even after selling their tokens, without the need for market prediction. This establishes a Provenance Value Amplification (PVA) framework where creators, buyers, and sellers collaborate to collectively increase value.

**Implementation Details:**
- The design and approach are left to the discretion of the assignee.
- ERC-5173 introduces a standardized profit-sharing model across the entire ownership history of an NFT, benefiting all market participants. It creates a "Flow of Provenance" where buyers and owners are rewarded for their contributions to price discovery.

**Reference:** https://github.com/ethereum/ERCs/blob/60569a1f8b57fea10340dc34602baf895a613daa/ERCS/erc-5173.md

**Comment by KevinMB0220** [comment] 2024-10-24 07:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi, I'm part of Dojo Coding. For this task, I will create a folder inside experimental/erc_5173_future_rewards and develop a system that implements ERC-5173, allowing owners to benefit from future price appreciation even after selling their tokens. The design will be based on a "Flow of Provenance" framework, where creators, buyers, and owners are rewarded for their contributions to price discovery. I will ensure the implementation follows the ERC-5173 standards for a profit-sharing model throughout the ownership history of the NFT.

**Comment by Mystic-Nayy** [comment] 2024-10-24 07:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

### How I plan on tackling this issue
To implement the `nFR` (Non-Fungible Rights) in the `experimental/erc_5173_future_rewards` folder:

1. **Set Up Structure:** Create necessary files and directories for contracts, tests, and documentation.
   
2. **Develop Smart Contract:** Implement the ERC-5173 standard, focusing on ownership transfer and profit-sharing logic for previous owners based on sales.

3. **Write Tests:** Ensure all functionalities work correctly, including ownership transfers and reward distributions.

4. **Document Implementation:** Clearly explain the architecture and usage of the contract.

5. **Collaborate and Review:** Share your work for feedback and iterate as needed before finalizing the implementation.

**Comment by DiegoB1911** [comment] 2024-10-24 07:58
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies.

### How I plan on tackling this issue
To solve this, I would:
1. Understand the ERC-5173 specification.
2. Design and implement the smart contract.
3. Test the implementation.
4. Document the code.

**Comment by saimeunt** [comment] 2024-10-24 08:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past, porting Solidity ERCs to Cairo eg. https://github.com/carbonable-labs/cairo-erc-7496 and https://github.com/carbonable-labs/cairo-erc-7498

### How I plan on tackling this issue
I will carefully read the ERC and proposed Solidity implementation and I'll implement the expected behavior in Cairo. I will then use Starknet Foundry to test if the implementation is correct.

**Comment by KevinMB0220** [comment] 2024-10-24 20:49
Hello, I have to unassign this issue since I was accepted in two others and I already started them, sorry for the inconvenience @0xandee

**Comment by Jemiiah** [comment] 2024-10-24 20:52
can I take this up @0xandee 🚀

**Comment by od-hunter** [comment] 2024-10-24 21:07
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

To solve this issue, I'll take the following steps:
1. I'll create and work inside `experimental/erc_5173_future_rewards` folder and initialize a Hardhat/Truffle project and install dependencies like OpenZeppelin.

2. Then I'll create an `ERC5173FutureRewards.sol` contract based on the ERC-721 standard and track ownership history using a struct (`OwnershipRecord`) containing owner, purchase price, and sale price.
3. Next I'll use recordSale(tokenId, salePrice) ⁠ to record the sale, transfer the NFT, and update the ownership history. I'll also use getRewardForOwner(tokenId, owner) ⁠ to calculate the reward for each previous owner based on price appreciation during their ownership period
4. Next, I'll store each owner's price contribution to the overall value in the history array. I'll calculate rewards based on the difference between purchase and sale prices.
5. Lastly, I'll write unit tests.

Please assign me I'm ready to work.

**Comment by Mystic-Nayy** [comment] 2024-10-24 21:29
Hi @0xandee i will like to take this issue, I’ve applied on how I’ll work on it when I am assigned

**Comment by sandragcarrillo** [comment] 2024-10-24 23:23
I’m interested in this one.

My background and how it can be leveraged:
I have been learning Cairo for the past months and contributing to some projects like Awesome Starknet.  Also I'm currently part of the HER DAO Starknet Basecamp.

How I plan on tackling this issue:
1. I would create the folder setup
2. Create the  ERC-5173 Cairo Contract Design
3. Create tests for the contract
4. Add documentation to explain the approach

**Comment by martinvibes** [comment] 2024-10-25 05:19
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by aniruddhaaps** [comment] 2024-10-25 05:58
I'm a cairo dev. A new-comer here, willing to and ready to contribute to solve the issue.

**Comment by 0xandee** [comment] 2024-10-28 08:42
GM @Jemiiah  just checking in, how're you doing?

**Comment by 0xandee** [comment] 2024-11-09 05:32
Hey we're re-open this issue :)

**Comment by JoE11-y** [comment] 2024-11-09 06:25
Can I get to work on this @0xandee

**Comment by od-hunter** [comment] 2024-11-09 06:35
> Hey we're re-open this issue :)

Hi @0xandee , please can I be assigned this?

**Comment by saimeunt** [comment] 2024-11-09 14:40
Hey @0xandee as a returning contributor I'd like to handle this one please!

**Closed** 2024-12-02 14:43 UTC
Labels: ODHack9
